group: deprecated-2017Q2

env:
  global:
    - LOGSTASH_DOCKER_IMAGE="logstash/logstash"
    - LOGSTASH_DOCKER_REGISTRY="docker.elastic.co"
    - LOGSTASH_DOCKER_VERSION="5.4.1"
    - LOGSTASH_DOCKER_ENV="XPACK_MONITORING_ENABLED=false"
    - LOGSTASH_PIPELINE_DIR="src/test/resources/logstash/pipeline"
    - LOGSTASH_LOGS_DIR="target/logs"

sudo: required

services:
  - docker

before_install:
  - "mvn clean package --quiet"
  - "mkdir -p ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}"
  - "docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}"
  - docker run -d
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_PIPELINE_DIR}:/usr/share/logstash/pipeline
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}:/tmp/logs
    -p 127.0.0.1:514:5555
    -p 127.0.0.1:514:5555/udp
    -e ${LOGSTASH_DOCKER_ENV}
    ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
  - sudo conntrack -F

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  except:
    - /^test.*/i

script: "mvn verify -DskipIntegrationTests=false"
