#group: deprecated-2017Q2

env:
  global:
    - LOGSTASH_DOCKER_IMAGE="logstash/logstash"
    - LOGSTASH_DOCKER_REGISTRY="docker.elastic.co"
    - LOGSTASH_DOCKER_VERSION="5.4.1"
    - LOGSTASH_DOCKER_ENV="XPACK_MONITORING_ENABLED=false"
    - LOGSTASH_PIPELINE_DIR="src/test/resources/logstash/pipeline"
    - LOGSTASH_LOGS_DIR="target/logs"

sudo: required

services:
  - docker

before_install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update#
#  - sudo apt-get -y install docker-ce 
#  - sudo apt-cache search docker-engine
#  - sudo apt-cache show docker-engine
#  - sudo apt-get -y --only-upgrade install docker-ce
#  - docker --version
#  - sudo apt-get remove -y docker-ce
#  - sudo apt-get install  -y docker-engine
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - sudo apt-get install -y conntrack
  - sudo conntrack -D -p udp
  - "mvn clean package --quiet"
  - "mkdir -p ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}"
  - "docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}"
  - docker run -d
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_PIPELINE_DIR}:/usr/share/logstash/pipeline
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}:/tmp/logs
    -p 127.0.0.1:514:5555
    -p 127.0.0.1:514:5555/udp
    -e ${LOGSTASH_DOCKER_ENV}
    ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
  - docker ps
  - "docker logs `docker ps | grep logstash | awk '{ print $1}'`" 
  - ls -al ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  except:
    - /^test.*/i

script:
  - "docker logs `docker ps | grep logstash | awk '{ print $1}'`"
  - "mvn verify -DskipIntegrationTests=false"
