#group: deprecated-2017Q2

env:
  global:
    - LOGSTASH_DOCKER_IMAGE="logstash/logstash"
    - LOGSTASH_DOCKER_REGISTRY="docker.elastic.co"
    - LOGSTASH_DOCKER_VERSION="5.4.1"
    - LOGSTASH_DOCKER_ENV="XPACK_MONITORING_ENABLED=false"
    - LOGSTASH_PIPELINE_DIR="src/test/resources/logstash/pipeline"
    - LOGSTASH_LOGS_DIR="target/logs"

sudo: required

services:
  - docker

before_install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update#
#  - sudo apt-get -y install docker-ce 
#  - sudo apt-cache search docker-engine
#  - sudo apt-cache show docker-engine
####
#  - sudo apt-get update
#  - sudo apt-get -y --only-upgrade install docker-ce
#  - sudo service docker restart
####
#  - docker --version
#  - sudo apt-get remove -y docker-ce
#  - sudo apt-get install  -y docker-engine
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
#  - sudo apt-get install -y conntrack
#  - sudo conntrack -D -p udp
  - sudo /sbin/ifconfig
#  - sudo sysctl -a
  - sudo iptables -L -t nat
#  - "mvn clean package --quiet"
  - "mkdir -p ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}"
#  - "docker pull ubuntu"
#  - "docker run --name ubuntu_bash  -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}:/tmp/logs --rm -i -t ubuntu touch /tmp/logs/ubuntu.test"
  - "docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}"
  - docker run -d
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_PIPELINE_DIR}:/usr/share/logstash/pipeline
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}:/tmp/logs
    -p 5555:5555/udp
    -e ${LOGSTASH_DOCKER_ENV}
    ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
  - sleep 30
  - docker ps
  - docker --version
  - "docker logs `docker ps | grep logstash | awk '{ print $1}'`" 
  - "docker port `docker ps | grep logstash | awk '{ print $1}'`"
  - sudo iptables -L -t nat
  - ls -al ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}
  - touch ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}/toto
  - sudo cat /etc/hosts
  - sudo iptables -L -t nat
  - "netstat -an"

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  except:
    - /^test.*/i

script:
  - "mvn verify -DskipIntegrationTests=false"
