#group: deprecated-2017Q2

env:
  global:
    - LOGSTASH_DOCKER_IMAGE="logstash/logstash"
    - LOGSTASH_DOCKER_REGISTRY="docker.elastic.co"
    - LOGSTASH_DOCKER_VERSION="5.4.1"
    - LOGSTASH_DOCKER_ENV="XPACK_MONITORING_ENABLED=false"
    - LOGSTASH_PIPELINE_DIR="src/test/resources/logstash/pipeline"
    - LOGSTASH_LOGS_DIR="target/logs"

sudo: required

services:
  - docker

before_install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update#
#  - sudo apt-get -y install docker-ce 
#  - sudo apt-cache search docker-engine
#  - sudo apt-cache show docker-engine
####
#  - sudo apt-get update
#  - sudo apt-get -y --only-upgrade install docker-ce
#  - sudo service docker restart
####
#  - docker --version
#  - sudo apt-get remove -y docker-ce
#  - sudo apt-get install  -y docker-engine
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
#  - sudo apt-get install -y conntrack
#  - sudo conntrack -D -p udp
  - ls -al /etc
  - sudo ls -al /etc/docker
  - sudo cat /etc/docker/key.json
  - sudo cat /etc/subuid
  - sudo |- echo "{\"userns-remap\": \"travis\"}" > /etc/docker/daemon.json
  - sudo service docker restart
  - sudo cat /etc/default/docker
  - sudo ps -aux | grep docker
  - sudo cat /lib/systemd/system/docker.service
#  - sudo ls -al /etc/systemd/system/docker.service.d
#  - sudo ls -al /etc/default/docker
  - sudo /sbin/ifconfig
  - "sudo sysctl -a"
  - sudo iptables -L -t nat
#  - "mvn clean package --quiet"
  - "mkdir -p ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}"
##########
# TEST UDP
##########
  - sudo apt-get -y install netcat
  - docker pull mendhak/udp-listener
  - docker run -d -p 127.0.0.1:5005:5005/udp --name udp-listener mendhak/udp-listener
  - echo -n test | nc -u 127.0.0.1 5005 &
  - echo -n test2 | nc -u localhost 5005 &
  - sleep 10
  - docker exec -it udp-listener netstat -an
  - docker logs udp-listener 
##########
  - "docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}"
  - docker run -d
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_PIPELINE_DIR}:/usr/share/logstash/pipeline
    -v ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}:/tmp/logs
    -p 127.0.0.1:5555:5555/udp
    -e ${LOGSTASH_DOCKER_ENV}
    --sysctl net.ipv6.conf.all.disable_ipv6=1
    --name logstash
    ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
##########
  - sleep 30
  - echo -n test3 | nc -u 127.0.0.1 5555 &
  - echo -n test4 | nc -u localhost 5555 &
  - id
  - docker exec -it logstash id
  - docker exec -it logstash ls -al /tmp/logs
  - docker exec -it logstash touch /tmp/logs/touch
  - whoami
##########
  - docker ps
  - docker --version
  - "docker logs logstash" 
  - "docker port `docker ps | grep logstash | awk '{ print $1}'`"
  - sudo iptables -L -t nat
  - ls -al ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}
  - touch ${TRAVIS_BUILD_DIR}/${LOGSTASH_LOGS_DIR}/toto
  - sudo cat /etc/hosts
  - sudo iptables -L -t nat
  - "netstat -an"
  - ls -al /var/log/

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  except:
    - /^test.*/i

script:
  - "mvn verify -DskipIntegrationTests=false -Djava.net.preferIPv4Stack=true"
